from fastapi import FastAPI, HTTPException

from app.models import InvestmentQuery, InvestmentResponse
from app.orchestration.graph import investment_advisor_graph
from app.monitoring.alerts import check_alert_conditions
import time
from app.monitoring.logger import log_workflow_result
app = FastAPI(
    title="Agentic AI Investment Advisor",
    description="Multi-agent AI system for personalized and compliant investment guidance",
    version="1.0.0",
)


@app.get("/health")
def health_check():
    return {"status": "healthy"}


@app.post("/investment/advice", response_model=InvestmentResponse)
def investment_advice(request: InvestmentQuery):
    """
    Accepts a customer investment query and sends it
    through the multi-agent investment advisory workflow.
    """

    try:
        start_time = time.perf_counter()
        result = investment_advisor_graph.invoke(
            {
                "customer_id": request.customer_id,
                "query": request.query,
            }
        )
        latency_ms = (time.perf_counter() - start_time) * 1000

        log_workflow_result(
            customer_id=request.customer_id,
            query=request.query,
            result=result,
            latency_ms=latency_ms,
        )
        check_alert_conditions(
            result=result,
            latency_ms=latency_ms,
        )

        return InvestmentResponse(
            response=result.get(
                "final_response",
                "The query could not be processed at this time.",
            ),
            explanation=result.get(
                "explanation",
                "The response was generated by the investment advisory workflow.",
            ),
            compliance_status=result.get(
                "compliance_result",
                "REQUIRES_REVIEW",
            ),
            compliance_reason=result.get(
                "compliance_reason",
                "No compliance reason was provided.",
            ),
        )

    except Exception as exc:
        print(f"Investment workflow error: {exc}")
        raise HTTPException(
            status_code=500,
            detail="Unable to process the investment query.",
        ) from exc