from fastapi import FastAPI, HTTPException

from app.models import InvestmentQuery, InvestmentResponse
from app.orchestration.graph import investment_advisor_graph


app = FastAPI(
    title="Agentic AI Investment Advisor",
    description="Multi-agent AI system for personalized and compliant investment guidance",
    version="1.0.0",
)


@app.get("/health")
def health_check():
    return {"status": "healthy"}


@app.post("/investment/advice", response_model=InvestmentResponse)
def investment_advice(request: InvestmentQuery):
    """
    Accepts a customer investment query and sends it
    through the multi-agent investment advisory workflow.
    """

    try:
        result = investment_advisor_graph.invoke(
            {
                "customer_id": request.customer_id,
                "query": request.query,
            }
        )

        return InvestmentResponse(
            response=result.get(
                "final_response",
                "The query could not be processed at this time.",
            ),
            explanation=result.get(
                "explanation",
                "The response was generated by the investment advisory workflow.",
            ),
            compliance_status=result.get(
                "compliance_result",
                "REQUIRES_REVIEW",
            ),
        )

    except Exception as exc:
        print(f"Investment workflow error: {exc}")
        raise HTTPException(
            status_code=500,
            detail="Unable to process the investment query.",
        ) from exc